// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useEffect, useRef } from "react";
// import { useGLTF, useAnimations } from "@react-three/drei";

// export default function Bot({ position, botActions, ...props }) {
//   const group = useRef();
//   const { nodes, materials, animations } = useGLTF("/robot.glb");
//   const { actions } = useAnimations(animations, group);

//   useEffect(() => {
//     botActions(actions);
//   }, [actions]);

//   useEffect(() => {
//     actions["hip_control|waving"]?.reset()?.fadeIn(0.5)?.play();
//   }, []);

//   return (
//     <group ref={group} position={position} {...props} dispose={null}>
//       <group name="Sketchfab_Scene">
//         <group
//           name="Sketchfab_model"
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={1.602}
//         >
//           <group
//             name="aa1e593268264a5fa14e6999f232b539fbx"
//             rotation={[Math.PI / 2, 0, 0]}
//             scale={0.01}
//           >
//             <group name="Object_2">
//               <group name="RootNode">
//                 <group
//                   name="torso"
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="torso_joint"
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="Cube003"
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="arms"
//                   position={[35.616, 155.844, 0]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="legs"
//                   position={[9.995, 99.126, 0]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="feet"
//                   position={[9.995, 7.523, -4.07]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="hands"
//                   position={[77.204, 156.166, -0.177]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="head"
//                   position={[0, 40.751, 0]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 />
//                 <group
//                   name="hip_control"
//                   position={[0, 0.755, 1.338]}
//                   rotation={[-Math.PI / 2, 0, 0]}
//                   scale={100}
//                 >
//                   <group name="Object_13">
//                     <primitive object={nodes._rootJoint} />
//                     <skinnedMesh
//                       name="Object_16"
//                       geometry={nodes.Object_16.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_16.skeleton}
//                     />
//                     <skinnedMesh
//                       name="Object_18"
//                       geometry={nodes.Object_18.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_18.skeleton}
//                     />
//                     <skinnedMesh
//                       name="Object_20"
//                       geometry={nodes.Object_20.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_20.skeleton}
//                     />
//                     <skinnedMesh
//                       name="Object_22"
//                       geometry={nodes.Object_22.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_22.skeleton}
//                     />
//                     <skinnedMesh
//                       name="Object_24"
//                       geometry={nodes.Object_24.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_24.skeleton}
//                     />
//                     <skinnedMesh
//                       name="Object_26"
//                       geometry={nodes.Object_26.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_26.skeleton}
//                     />
//                     <skinnedMesh
//                       name="Object_28"
//                       geometry={nodes.Object_28.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_28.skeleton}
//                     />
//                     <skinnedMesh
//                       name="Object_30"
//                       geometry={nodes.Object_30.geometry}
//                       material={materials.material}
//                       skeleton={nodes.Object_30.skeleton}
//                     />
//                     <group
//                       name="Object_15"
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                     <group
//                       name="Object_17"
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                     <group
//                       name="Object_19"
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                     <group
//                       name="Object_21"
//                       position={[35.616, 155.844, 0]}
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                     <group
//                       name="Object_23"
//                       position={[9.995, 99.126, 0]}
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                     <group
//                       name="Object_25"
//                       position={[9.995, 7.523, -4.07]}
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                     <group
//                       name="Object_27"
//                       position={[77.204, 156.166, -0.177]}
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                     <group
//                       name="Object_29"
//                       position={[0, 40.751, 0]}
//                       rotation={[-Math.PI / 2, 0, 0]}
//                       scale={100}
//                     />
//                   </group>
//                 </group>
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/robot.glb");

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Bot({ position, botActions, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/bot.glb");
  const { actions } = useAnimations(animations, group);

    useEffect(() => {
      botActions(actions);
    }, [actions]);

  useEffect(() => {
    actions["Animation"].play();
  }, []);
  return (
    <group position={position} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Alembic" scale={0.025}>
          <mesh
            name="lights01"
            castShadow
            receiveShadow
            geometry={nodes.lights01.geometry}
            material={materials["Material.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={39.37}
          />
          <mesh
            name="Object001"
            castShadow
            receiveShadow
            geometry={nodes.Object001.geometry}
            material={materials["Material.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={39.37}
          />
          <mesh
            name="Object002"
            castShadow
            receiveShadow
            geometry={nodes.Object002.geometry}
            material={materials["Material.001"]}
            position={[-2.328, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-39.37}
          />
          <mesh
            name="Object003"
            castShadow
            receiveShadow
            geometry={nodes.Object003.geometry}
            material={materials["Material.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={39.37}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/bot.glb");
